version: "3.9"
services:
  runner:
    build: 
      context: .
      dockerfile: ./aatp/infra/runner/Dockerfile
    volumes:
      - ./aatp/peerbook_webrtc:/runner
      - ./aatp/result:/result
    environment:
      PWARGS: ${PWARGS--x}
    depends_on:
      - peerbook
      - terminal7
      - webexec
  terminal7:
    image: halverneus/static-file-server:latest
    environment:
      PORT: 80
    volumes:
      - ./dist:/web
  webexec:
    build:
      context: .
      dockerfile: ./aatp/infra/webexec/Dockerfile
    depends_on:
      - peerbook
    volumes:
      - ./aatp/peerbook_webrtc/webexec_conf:/conf
  peerbook:
    build:
      context: .
      dockerfile: ./aatp/infra/peerbook/Dockerfile
    expose:
      - "17777"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis:6379
  redis:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]  # disable persistence

